---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node

inputs:
  - name: training-cf-ui   

outputs:
  - name: training-cf-ui-dist

run:
  path: training-cf-ui/ci/tasks/build-artifact.sh