---
jobs:
- name: ci-training-cf-ui
  public: true
  serial: true
  plan:
  - get: training-cf-ui
    trigger: true
  - task: build-training-cf-ui
    file: training-cf-ui/ci/tasks/build-artifact.yml

resources:
- name: training-cf-ui
  type: git
  source:
    uri: https://github.com/masalinas/training-cf-ui.git
    branch: master