---
jobs:
- name: ci-training-cf-ui
  public: true
  serial: true
  plan:
  - get: training-cf-ui
    trigger: true
  - task: build-training-cf-ui
    file: training-cf-ui/ci/tasks/build-artifact.yml
  - put: deploy-training-cf-ui
    params:
      manifest: training-cf-ui/manifest-cloud.yml
      path: training-cf-ui/build

resources:
- name: training-cf-ui
  type: git
  source:
    uri: https://github.com/masalinas/training-cf-ui.git
    branch: master

- name: deploy-training-cf-ui
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: ((cf-user))                
    password: ((cf-password))
    organization: ((cf-org))
    space: ((cf-space))
    skip_cert_check: false    